#!/bin/bash

# Build script for FleetOnRails API
echo -e "\n\n"
echo -e "####################################"
echo -e "#        FleetOnRails API          #"
echo -e "#          Build Script            #"
echo -e "####################################"

# Install dependencies
echo -e "\n\nInstalling dependencies"
bundle install || { echo 'my_command failed' ; exit 1; }

# Create test db
echo -e "\n\nCreating test database"
bundle exec rake db:migrate:reset RAILS_ENV=test || { echo 'my_command failed' ; exit 1; }

# Run tests
echo -e "\n\nRunning RSpec tests"
bundle exec rspec || { exit 1; }
