#! /bin/bash
# Build script for FleetOnRails API
echo -e "\n\n"
echo -e "####################################"
echo -e "#        FleetOnRails API          #"
echo -e "#          Build Script            #"
echo -e "####################################"

# Install dependencies
echo -e "\n\nInstalling dependencies"
mkdir ~/bundle
bundle install --path ~/bundle

# Create test db
echo -e "\n\nCreating test database"
bundle exec rake db:create RAILS_ENV=test
bundle exec rake db:migrate RAILS_ENV=test

# Run tests
echo -e "\n\nRunning RSpec tests"
bundle exec rspec

# Upload coverage report to Apache
cd coverage/ && rsync -rvz --delete ./* root@web.raven.com:/var/www/coverage.raven.com/ && cd ..
